### ISSUE TITLE
Why emit an error when `maxDataSize` is reached?

### ISSUE THREAD

**Issue by triccardi-systran** [felixge/node-combined-stream#22]
Why emit an error event when `maxDataSize` is reached? 
Shouldn't it just back-pressure the associated source stream (probably by pausing it)?

**Comment by apechimp** [comment]
The error regarding `maxDataSize` is only emitted when a stream has been created before being concatenated, pause mode was not used, the stream has not been piped to anything yet, and the stream managed to buffer more than `maxDataSize`. In this scenario, we can't use the back pressure of `pipe` because we haven't piped it yet, but if you'd like the stream to pause, simply use the `pauseStreams` option (enabled by default).

**Comment by triccardi-systran** [comment]
Ok, the default behavior is thus fine, thanks.
