### ISSUE TITLE
Streams aren't paused when added using append(callback) method

### ISSUE THREAD

**Issue by petrosagg** [felixge/node-combined-stream#24]
The following code will print only the contents of FILE1
```javascript
stream1 = fs.createReadStream(FILE1)
stream2 = fs.createReadStream(FILE2)

combinedStream = CombinedStream.create()
combinedStream.append(function(next) {
        next(stream1);
});
combinedStream.append(function(next) {
        next(stream2);
});
combinedStream.pipe(process.stdout)
```

This is because the streams added via `next()` calls aren't paused before running `on('data')` on them, which triggers a switch of the Stream API.

**Comment by apechimp** [comment]
This is actually working as intended. If you want to create your streams ahead of time and cat them, you shouldn't be using the callback api. The callback api is for creating the stream on demand. The intended use is something like the following.

```javascript
combinedStream = CombinedStream.create()
combinedStream.append(function(next) {
        next(fs.createReadStream(FILE1));
});
combinedStream.append(function(next) {
        next(fs.createReadStream(FILE2));
});
combinedStream.pipe(process.stdout)
```

Here, the file streams aren't created until the combined stream is ready to read them, and since it's ready to read them, there's no need to worry about pausing.
