### ISSUE TITLE
deprecate this?

### ISSUE THREAD

**Issue by zhuangya** [felixge/node-combined-stream#33]
more than two years later, #21 still has no clue.

ever consider deprecate this module?

**Comment by felixge** [comment]
This module is still being maintained as specified in [the license](https://github.com/felixge/node-combined-stream/blob/master/License#L13-L19) 😅.

IMO the "time since last commit" list of "open issues" should be enough for anybody that wants to decide if this code is still worth their time or not. I certainly don't have any time manage the maintained/unmaintained status of my 100+ repos ...
